volumes:
  bloodhound_local_postgres_data: {}
  bloodhound_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bloodhound_local_django
    container_name: bloodhound_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bloodhound_local_production_postgres
    container_name: bloodhound_local_postgres
    volumes:
      - bloodhound_local_postgres_data:/var/lib/postgresql/data
      - bloodhound_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "6543:5432" # NB - Allows access to postgres from outside $ psql -U dev -h localhost postgres -p 6543

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: bloodhound_local_mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
