services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bloodhound_local_django
    container_name: bloodhound_local_django
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.envs/.local/.django
    ports:
      - '8000:8000'
    command: /start
